### PR TITLE
Merge recipelist into dev

### PR DESCRIPTION
**Pull request by echuchu**

### CODE REVIEW

**Comment by echuchu** [comment]
example_p.json to be updated from CI branch (so the failing checks involving partial_search can be ignored for now)

**Review by SeanXYTan — APPROVED** [review]

**Comment by starshine-bcit** [comment]
Do we plan to use the save_recipes_to_file method in production, or is it just for internal use?

**Comment by echuchu** [comment]
> Do we plan to use the save_recipes_to_file method in production, or is it just for internal use?

I don't think it's needed in production, it can be removed afterwards when we're done with it I guess? Same thing with the adding dietary labels, once it's added and written, it can be altered to not append the label probably? I think? Lol

**Comment by starshine-bcit** [comment]
> > Do we plan to use the save_recipes_to_file method in production, or is it just for internal use?
> 
> I don't think it's needed in production, it can be removed afterwards when we're done with it I guess? Same thing with the adding dietary labels, once it's added and written, it can be altered to not append the label probably? I think? Lol

No, it's all good. Was just checking because I had to fix all relative paths for production environment. If we're just using it internally then it doesn't matter.

**Review by starshine-bcit — APPROVED** [review]

**Comment by starshine-bcit** [comment]
The only suggestion I have here is to update the csv file to not include the colons.
I know the contents are just being copied into constant arrays, so it doesn't really matter..

**Pull request merged**
