### PR TITLE
Merge branch qtw4 into dev for final deliverable

### PR DESCRIPTION
**Pull request by starshine-bcit**
- Modified recipie.spec to build all current modules
- Refactor init to support loading
- Add loading bar functionality
- Add help window functionality and some missing docstrings
- Update formatting a bit more for 1.0 release
- Remove orphaned functions
- Add interesting loading messages

### CODE REVIEW

**Review by echuchu — COMMENTED** [review]
image

No TT_TT

**Review by echuchu — COMMENTED** [review]
We can update the pytests so every RecipeList instantiation also takes a filler callback function so it doesn't yell anymore, not sure if we really need to explicitly test it tho

Maybe we update that first before merging into dev?

Also maybe update the docstrings in RecipeList to reflect the callback addition and is tlen...total_length? Maybe just a comment to make that explicit for what it is

Oh I mentioned this in the FAQ but I guess it can be here too, I barely see the loading bar because it's barely 2 seconds to load for me ^^"

**Comment by SeanXYTan** [comment]
Wowee that's a lot of broken tests, I'll update the pytests if we need to do that first, but like Eva mentioned, it does actually only take 2-3 seconds to start up now

**Comment by starshine-bcit** [comment]
Okay, I'll update the docs @echuchu while I guess @SeanXYTan can update the tests?

Edit: Yeah, I wondered if it was only me with the quick load-up now, but great!

**Review by echuchu — APPROVED** [review]
wooo passsesss

**Review by SeanXYTan — APPROVED** [review]

**Pull request merged**
